[package]
name = "geodiffr-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "geodiffr-cli"
path = "src/bin/main.rs"

[dependencies]
anyhow = "1.0.82"
clap = "4.5.4"
geojson = "0.24.1"
